<a href="https://colab.research.google.com/github/h4rz/NumPy/blob/master/NumPy%20Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Load in NumPy (remember to pip install numpy first)

In [2]:
import numpy as np

### The Basics

In [3]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [15]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]
 [6. 5. 4.]]


In [16]:
# Get Dimension
print(a.ndim)
print(b.ndim)

1
2


In [11]:
# Get Shape
print(a.shape) # 3 columns, 1 row
print(b.shape) # 3 columns, 2 row

(3,)
(2, 3)


In [17]:
# Get Type
a.dtype

dtype('int32')

In [18]:
# Get Size
a.itemsize

4

In [20]:
# Get total size
a.nbytes # a.size * a.itemsize

12

In [21]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [22]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [24]:
# Get a specific element [r, c]
a[1, 5]

13

In [27]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [31]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2] #a[0, 1:6:2] 

array([2, 4, 6])

In [ ]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [33]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Get specific element (work outside in)
b[0,1,1]

4

In [34]:
# replace 
b[:,1,:] = [[9,9],[8,8]]

In [35]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [36]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [43]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [44]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [47]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.45350107, 0.47220051],
       [0.33077429, 0.62147406],
       [0.77484739, 0.10275741],
       [0.72238517, 0.60795015]])

In [48]:
# Random Integer values randint(start, end, size)
np.random.randint(-4,8, size=(3,3))

array([[-1,  0, -4],
       [-2,  6,  0],
       [-1,  6, -2]])

In [49]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [55]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [69]:
output = np.ones((5,5))
print(output)

center = np.zeros((3,3))
center[1,1] = 9
print(center)

output[1:4,1:4] = center
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [70]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


### Mathematics

In [71]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [72]:
a + 2

array([3, 4, 5, 6])

In [73]:
a - 2

array([-1,  0,  1,  2])

In [74]:
a * 2

array([2, 4, 6, 8])

In [75]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [76]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [77]:
a ** 2

array([ 1,  4,  9, 16])

In [78]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [79]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [80]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [85]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
np.min(stats)

1

In [87]:
np.max(stats, axis=1)

array([3, 6])

In [90]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [95]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [96]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [97]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [99]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

SyntaxError: ignored

##### Boolean Masking and Advanced Indexing

In [ ]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])